fix(overlay): Focuses the first tabbable element inside a overlay con…
dynatrace-oss/barista pull request #1743
Opened 2020-10-15 09:05 UTC by rowa-audil

### <strong>Pull Request</strong>

Fixes a bug that caused the last tabbable item in an overlay context to be focused. The list of elements in the overlay was scrolled to the bottom as the focus is set to the last element.

_**Fixed**_ by focusing the first tabbable item

fixes #1649 

#### Type of PR

Bugfix (non-breaking change which fixes an issue)

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2020-10-15 09:34 UTC, ffriedl89 reviewed
What is focused now initially?

2020-10-15 10:10 UTC, rowa-audil commented
@ffriedl89 The close button (X) of the overlay

2020-10-15 12:54 UTC, ffriedl89 commented
> @ffriedl89 The close button (X) of the overlay

I know that initially we did not want to have the x focused right away, since the user's first action is not going to be closing the context dialog right away. Could you change the source order so that the x is not the first but the last element in the context dialog?

2020-10-16 07:10 UTC, lukasholzer approved these changes

2020-10-16 07:10 UTC, lukasholzer commented on apps/components-e2e/src/components/context-dialog/context-dialog.po.ts
> +export const isCloseButtonActiveElement = ClientFunction(() => {
NIT: please add jsdoc what you are doing there because it is not that describing when you see this selector `('.dt-context-dialog-trigger')`

2020-10-16 07:10 UTC, lukasholzer commented on libs/barista-components/context-dialog/src/context-dialog.ts
> +        .focusFirstTabbableElementWhenReady()
I guess It worked then as expected :D

2020-10-19 05:59 UTC, ffriedl89 requested changes

2020-10-19 05:59 UTC, ffriedl89 commented on libs/barista-components/context-dialog/src/context-dialog.html
>      <ng-content select="dt-context-dialog-footer"></ng-content>
Please also move the footer up in the source order. All areas where the user could add content should be before the abort button.

2020-10-20 06:09 UTC, ffriedl89 submitted a review, later dismissed

2020-10-20 06:12 UTC, ffriedl89 commented
Needs a rebase - please change scope from overlay to context-dialog

2020-10-20 07:26 UTC, ffriedl89 approved these changes

2020-10-20 09:43 UTC, rowa-audil commented
Mistakenly added a commit 😅

2020-10-20 11:28 UTC, ffriedl89 approved these changes

2020-10-21 05:30 UTC, merged