Fix strict mode type coercion
dynatrace-oss/barista pull request #1918
Opened 2021-01-14 14:44 UTC by tomheller

### <strong>Pull Request</strong>

Oh the funs with strict mode 😄 This should do the trick.

#### Type of PR
Refactor

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2021-01-14 14:51 UTC, ffriedl89 requested changes
Thank you so much for this, going over all of them. Sorry I had to leave our liveshare session 😞

2021-01-14 14:51 UTC, ffriedl89 commented on package-lock.json
> +        "core-js": {
Do you have an idea why the package.lock was changed? I guess we can revert those right?

2021-01-15 07:38 UTC, thomaspink approved these changes

2021-01-15 08:59 UTC, rowa-audil approved these changes
LGTM 🐘

2021-01-18 06:33 UTC, tomheller commented
Rebased and updated with changes from #1912

2021-01-19 07:53 UTC, ffriedl89 approved these changes

2021-01-19 07:55 UTC, merged