chore(workspace): Bump rules_nodejs to 3.0.0, new Jest rule based on Wave
dynatrace-oss/barista pull request #1949
Opened 2021-02-01 16:06 UTC by SkaillZ

Fixes an issue with Jest tests on Windows.

#### Type of PR

Other

2021-02-01 16:50 UTC, SkaillZ commented
Draft because the CI is acting up, local testing should already work.

2021-02-02 06:32 UTC, tomheller requested changes
Looks good, linting does not seem to be set up correctly though.

2021-02-02 06:32 UTC, tomheller commented on tools/bazel_rules/jest/.eslintrc.json
> +{
We're not using eslint in barista. This is probably an artifact from copying it, right?
Can you make sure that linting is set up correctly for this project. 

With this, you should see the license header failing, as this is not yet changed in barista. 
I'm opening the PR right now.

2021-02-08 11:34 UTC, SkaillZ commented
Blocked by #1966

2021-02-15 13:07 UTC, tomheller approved these changes

2021-02-16 14:07 UTC, tomheller submitted a review, later dismissed

2021-03-04 06:23 UTC, lukasholzer approved these changes

2021-03-15 10:30 UTC, tomheller approved these changes

2021-03-15 12:36 UTC, merged