feat(filter-field): The id a consumer provides via data of an option …
dynatrace-oss/barista pull request #1985
Opened 2021-02-16 08:25 UTC by thomaspink

feat(filter-field): The id a consumer provides via data of an option will be used to track it over time when using the DefaultDataSource.

2021-03-08 15:28 UTC, ffriedl89 requested changes
No real concerns, looks really good 👍

2021-03-08 15:28 UTC, ffriedl89 commented on libs/barista-components/quick-filter/src/state/reducer.ts
> +      return { ...stateBackup, dataSource: action.payload };
```suggestion
      return { ...state, dataSource: action.payload };
```
You can spread the state directly, no need to store it in a variable :)

2021-03-08 15:44 UTC, tomheller approved these changes

2021-03-08 16:46 UTC, ffriedl89 approved these changes

2021-03-09 08:51 UTC, tomheller approved these changes

2021-03-09 08:52 UTC, merged