Bugfix/apm 300499 event field minor bug fixes
dynatrace-oss/barista pull request #2121
Opened 2021-05-12 11:56 UTC by kacper-olszanski

### <strong>Pull Request</strong>

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Type of PR

#### Checklist

- [ ] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-05-12 13:50 UTC, tomheller commented
Hi @kacper-olszanski!

Could you be a bit more specific other than _Minor bug fixes_ in the pull request and also the commit message. The issue template is here to be filled out so we and others who are reading the PR get a grasp of what you are actually trying to do.

2021-05-12 13:59 UTC, kacper-olszanski commented
> Could you be a bit more specific other than _Minor bug fixes_ in the pull request and also the commit message. The issue template is here to be filled out so we and others who are reading the PR get a grasp of what you are actually trying to do.

@tomheller 
The description of the changes is on Jira but I can copy paste it here:

fixed bugs:
- legend margin-top not working
- heatfields should be merged when start and end of heatfields are matching
- min length for fields should be set if they are too short to see

2021-05-12 14:05 UTC, tomheller commented
@kacper-olszanski Thank you. The changes in general look good. Could you please squash your changes to get rid of the merge commit and reword the commit `fix(event-chart): Fixes various issues with the legend and heatfields.`

2021-05-17 07:44 UTC, thomaspink requested changes
Thank you for your contribution. Before we can merge it please remove the marked console logs from the src.

2021-05-17 07:44 UTC, thomaspink commented on libs/barista-components/event-chart/src/merge-and-path/merge-events.ts
> +      console.log({
Please remove this debug log

2021-05-20 08:05 UTC, thomaspink approved these changes

2021-05-25 06:26 UTC, ffriedl89 approved these changes

2021-05-25 06:37 UTC, thomaspink approved these changes

2021-05-25 06:54 UTC, ffriedl89 commented
PR seems to have issues in the Git changeset, moved the changes over to a new branch and will merge #2132

2021-05-25 06:54 UTC, closed without merging