fix(combobox): Fixes the border inside a form-field
dynatrace-oss/barista pull request #2341
Opened 2021-12-06 15:33 UTC by rowa-audil

### <strong>Pull Request</strong>
<hr>

#### Type of PR

Bugfix (non-breaking change which fixes an issue)

#### Checklist

- [ ] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-12-07 08:05 UTC, tomheller commented
Could you create an example that shows this in action?

2021-12-07 09:18 UTC, ffriedl89 commented
The select is 30px high with this PR the combobox is 32px high and therefore the text is misaligned. @rowa-audil Please check that again so that the combobox features the same height as the select does. 
![image](https://user-images.githubusercontent.com/2905693/145001266-343e295c-27fb-45cd-8402-2db49655919c.png)
![image](https://user-images.githubusercontent.com/2905693/145001317-ce25f97c-fbf9-471d-ba1e-566cd8b50705.png)

2021-12-07 09:18 UTC, ffriedl89 requested changes

2021-12-07 09:18 UTC, ffriedl89 commented on libs/barista-components/experimental/combobox/src/combobox.scss
> +  height: auto;
Please check those changes since the height is now wrong.

2021-12-23 08:57 UTC, thomaspink approved these changes

2021-12-23 11:49 UTC, ffriedl89 approved these changes

2021-12-23 12:06 UTC, merged