fix(table): Export handles newlines & expand rows.
dynatrace-oss/barista pull request #2503
Opened 2022-05-05 17:01 UTC by LucasHocker

### <strong>Pull Request</strong>

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Type of PR

Bugfix (non-breaking change which fixes an issue) 

#### Checklist

- [ X] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ X] Lint and unit tests pass locally with my changes
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] I have added necessary documentation (if appropriate)

2022-05-11 11:53 UTC, ffriedl89 requested changes

2022-05-11 11:53 UTC, ffriedl89 commented on libs/barista-components/table/src/table.ts
> +          if (cells[j].matches('.dt-expandable-cell')) txt = '';
```
let txt = cells[j].classList.contains('.dt-expandable-cell') ? '' : cells[j].innerText;
```

2022-05-11 11:53 UTC, ffriedl89 commented on libs/barista-components/table/src/table.ts
> +        val = val.replace(/[\n\r\t]/g, ' ');
Please add a comment what you are replacing here with this regex. I am really bad at regex :D

2022-05-11 12:54 UTC, Sherif-Elhefnawy requested changes

2022-05-11 12:54 UTC, Sherif-Elhefnawy commented on libs/examples/src/table/table-expandable-rows-example/table-expandable-rows-example.html
> +  [showExportButton]="true"
Please don't add export here. Either create a new example for exporting + expandable row or update one of the export stories to have the expandable rows

2022-05-13 06:13 UTC, ffriedl89 approved these changes

2022-05-13 06:29 UTC, Sherif-Elhefnawy approved these changes

2022-05-16 07:22 UTC, merged

2022-05-16 07:59 UTC, Sherif-Elhefnawy commented
Cherry picked into:
10.7.x: 4a06d1add9869a7f437430a274e656ea4ee547ce