feat(filter-field): Adding keyboard functionality to multiselect dropbox
dynatrace-oss/barista pull request #2571
Opened 2022-08-17 09:01 UTC by manulopez2dynatrace

### <strong>Pull Request</strong>

<hr>

#### Type of PR

Feature (non-breaking change which adds functionality)
Breaking change (fix or change that would cause existing functionality to not work as expected) 

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Changes

User now is able to navigate from the filter bar to the multiselect options and the other way around, due to that, the auto focus is not working anymore (autoActiveFirstOption) as the focus is set via arrow key navigation.

Cases to consider: 

***Acceptance Criteria 1***
HAVING the filter bar
THEN selecting a multiselect filter
AND start typing
THEN no option should be focused by default
THEN the user press the down arrow key
AND the first option should be focused

***Acceptance Criteria 2***
HAVING the filter bar
THEN selecting a multiselect filter
AND start typing
THEN no option should be focused by default
THEN the user press the up arrow key
THEN it scrolls down to the end of the list
AND the last option must be focused

***Acceptance Criteria 3***
HAVING the first multiselect option focused
THEN the user press the up arrow key
AND the filter field should be focused
AND no option in the list should be focused

***Acceptance Criteria 4***
HAVING the last multiselect option focused
THEN the user press the down arrow key
AND the filter field should be focused
AND no option in the list should be focused

*Note: Navigating through the options with the arrow keys should be still working as it is at this moment*

2022-08-17 14:35 UTC, Sherif-Elhefnawy commented
@manulopez2dynatrace, seems that the dropdown in case of Multi-select stays open on hitting Tab, which shouldn't be the case.

2022-08-18 13:19 UTC, manulopez2dynatrace commented on libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select-trigger.ts
> +      this.resetActiveItemAndKeyManagerLimitsOnPanel();
Add comment about why this was done.

2022-08-18 13:35 UTC, manulopez2dynatrace commented on libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select-trigger.ts
> -      this._resetActiveItem();
Multi-select panel should close on pressing TAB

2022-08-18 13:36 UTC, manulopez2dynatrace commented on libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select-trigger.ts
> +        this.element._keyManager.activeItem
Add comment about what this does

2022-08-18 13:56 UTC, Sherif-Elhefnawy requested changes

2022-08-18 13:56 UTC, Sherif-Elhefnawy commented on libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
> -  @Input()
@ffriedl89, how do you feel about the whole auto focus removal?

The issue is that the Multi-select is kind of broken due to the following:
1- Auto focus only works the first time the panel is opened. If the user closes the panel and then opens it again, no option is auto focused. 
2- While Panel is open, pressing Tab DOESN'T close the panel and just tabs through normally while keeping the panel open.
3- Entering a text which contains a space, while having an option in focus, caused the input not to accept space as a valid character.

2022-08-18 13:56 UTC, Sherif-Elhefnawy commented on libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts
> +      inputEl,
```suggestion
      inputElement,
```

2022-08-18 13:56 UTC, Sherif-Elhefnawy commented on libs/barista-components/filter-field/src/filter-field.html
> +        loading ||
Move this into a method :)

2022-08-18 13:56 UTC, Sherif-Elhefnawy commented on libs/barista-components/filter-field/src/filter-field.scss
> +  &.dt-not-blinking {
You don't need this

2022-08-29 13:04 UTC, Sherif-Elhefnawy approved these changes

2022-08-29 13:44 UTC, Sherif-Elhefnawy requested changes
- Please squash all commits into one

2022-08-29 14:19 UTC, Sherif-Elhefnawy approved these changes

2022-08-29 14:53 UTC, merged