feat(tag-add): Add possibility to customise add tag button label and …
dynatrace-oss/barista pull request #2596
Opened 2022-09-29 14:46 UTC by anntr

…overlay header independently.

### <strong>Pull Request</strong>

Motivation: PS-3788

This PR adds possibility to define 'Add tag' and overlay header title independently, as well as making submit button label 'Add' configurable. 

After changes: 
<img width="469" alt="Screenshot 2022-09-29 at 16 29 55" src="https://user-images.githubusercontent.com/7198185/193062613-b9e06989-7fe0-4cc0-b1ea-03c4dc59d26b.png">
<img width="655" alt="Screenshot 2022-09-29 at 16 30 06" src="https://user-images.githubusercontent.com/7198185/193062629-87e92735-efed-4f9e-a325-c2deec02eb45.png">

<hr>

Please choose the type appropriate for the changes below: <br>

#### Type of PR

Feature

#### Checklist

- [ ] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2022-10-05 08:25 UTC, Sherif-Elhefnawy requested changes

2022-10-05 08:25 UTC, Sherif-Elhefnawy commented on libs/barista-components/tag/src/tag-add/tag-add.ts
> +  @Input() buttonLabel?: string;
```suggestion
  @Input() label?: string;
```

2022-10-05 08:25 UTC, Sherif-Elhefnawy commented on libs/barista-components/tag/src/tag-add/tag-add.html
> +    [title]="buttonLabel ?? title"
```suggestion
```
You don't need to provide a title for the button if you provide a text for it :)

2022-10-05 08:25 UTC, Sherif-Elhefnawy commented on libs/barista-components/tag/src/tag-add/tag-add.ts
> +   * Title of the button overlay input.
```suggestion
   * Used to override the label for the button that triggers the Overlay.
```

2022-10-05 08:25 UTC, Sherif-Elhefnawy commented on libs/barista-components/tag/src/tag-add/tag-add.ts
> +  /** Title of the submit button in add-tag overlay input. */
```suggestion
  /** Used to override the label of the submit button in add-tag Overlay */
```

2022-10-05 08:34 UTC, Sherif-Elhefnawy commented
Could I bother you by adding an additional example for overriding the labels under libs/examples/src/tag?
Let's say with a name such as `tag-override-labels`,
You can see these examples via running `npm run demos`.

2022-10-06 07:30 UTC, Sherif-Elhefnawy commented on libs/barista-components/tag/src/tag-add/tag-add.html
> +    [title]="buttonLabel ?? title"
Now I see the dilemma, thanks for the clarification. Let's keep that title attribute then on the button.

2022-10-06 07:38 UTC, Sherif-Elhefnawy commented
Thank you for adapting the changes. I have played around with the attributes and we need to truncate the text in the overlay as shown in the following images:
![image](https://user-images.githubusercontent.com/59170440/194246207-595f167d-0b11-4f8f-ab9b-9baa66e5d81a.png)
![image](https://user-images.githubusercontent.com/59170440/194246271-62dc3ad5-eaf4-4ff4-aefe-aacc41efc033.png)
![image](https://user-images.githubusercontent.com/59170440/194246310-89775e14-f2c7-4dbf-9198-a28cbd03eff2.png)

2022-10-10 05:20 UTC, anntr commented
Long titles and buttons are now truncated: 
![Screenshot 2022-10-08 at 11 10 56](https://user-images.githubusercontent.com/7198185/194802841-d7fdc414-02b3-477b-b2f3-db8bfc541455.png)

If form is not custom and submit label is too long to be displayed inline, button drops to next line 
![Screenshot 2022-10-10 at 07 20 12](https://user-images.githubusercontent.com/7198185/194803011-224052e1-91c0-4d0f-aef9-649df7f40678.png)

2022-10-10 05:20 UTC, anntr commented
Long titles and buttons are now truncated: 
![Screenshot 2022-10-08 at 11 10 56](https://user-images.githubusercontent.com/7198185/194802841-d7fdc414-02b3-477b-b2f3-db8bfc541455.png)

If form is not custom and submit label is too long to be displayed inline, button drops to next line 
![Screenshot 2022-10-10 at 07 20 12](https://user-images.githubusercontent.com/7198185/194803011-224052e1-91c0-4d0f-aef9-649df7f40678.png)

2022-10-17 08:36 UTC, Sherif-Elhefnawy commented
Thank you for adapting the changes @anntr.

2022-10-17 08:36 UTC, Sherif-Elhefnawy approved these changes

2022-10-20 07:50 UTC, tomheller approved these changes

2022-10-27 10:11 UTC, merged

2022-10-27 10:17 UTC, Sherif-Elhefnawy commented
cherry picked into:
10.9.0: 67e399be3b86d86ac229128a8918e397c7a33a27
master: c4e4115f3ca4489dedc6c560dcdffbab75d64adb