feat(highlight): Allow highlighting multiple terms in one go
dynatrace-oss/barista pull request #2600
Opened 2022-10-05 08:20 UTC by bartoszbobin

#### Type of PR

Feature (non-breaking change which adds functionality)

#### Checklist

- [] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [] Lint and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have added necessary documentation (if appropriate)

2022-10-05 09:07 UTC, Sherif-Elhefnawy requested changes

2022-10-05 09:07 UTC, Sherif-Elhefnawy commented on libs/barista-components/highlight/src/highlight.ts
> +function createTermsRegExp(terms: string[], caseSensitive: boolean): RegExp {
Please add jsDoc comment for this new function

2022-10-05 09:07 UTC, Sherif-Elhefnawy commented on libs/examples/src/highlight/highlight-term-array-example/highlight-term-array-example.html
> +  eros. Integer viverra tempor lacinia. Aliquam ac nibh consectetur, auctor
You need to add this file declaration in `libs/examples/src/index.ts` as well as add a routing link in `apps/demos/src/app-routing.module.ts`

2022-10-05 09:13 UTC, Sherif-Elhefnawy commented
Running `npm run format` should help you with the formatting check error, there seems to be an issue with `highlight.spec.ts`

2022-10-05 11:46 UTC, bartoszbobin commented on libs/barista-components/highlight/README.md
> +```html
Done

2022-10-05 11:48 UTC, bartoszbobin commented
> Running `npm run format` should help you with the formatting check error, there seems to be an issue with `highlight.spec.ts`

Unfortunately 46 files have been changed (mostly specs) but not `highlight.spec.ts`

2022-10-06 08:00 UTC, Sherif-Elhefnawy commented
Hi, I pushed changes for formatting on this commit/branch that should help with the issue with the highlight.spec.ts https://github.com/dynatrace-oss/barista/commit/895656dd1bc6e54c8a09082471a5a72ccc7e7554#diff-d14ea366c314794bd31fe9e4b765acbb7efb5f815ec9136bbfb552cd0350ae59

2022-10-06 08:03 UTC, Sherif-Elhefnawy commented on libs/examples/src/highlight/highlight-term-array-example/highlight-term-array-example.html
> +  eros. Integer viverra tempor lacinia. Aliquam ac nibh consectetur, auctor
Please don't forget to add the nav link to` app-routing.module.ts` and `nav-items.ts` as was done here: https://github.com/dynatrace-oss/barista/pull/2596/files#diff-ffeda48d19c6203493253e37af0053e5732bc3952ede6423d1f5544919939abc

2022-10-17 08:02 UTC, Sherif-Elhefnawy commented
@bartoszbobin, thank you for fixing the formatting issue you had, please don't forget to add the nav link to app-routing.module.ts and nav-items.ts as was done here for your example: https://github.com/dynatrace-oss/barista/pull/2596/files#diff-ffeda48d19c6203493253e37af0053e5732bc3952ede6423d1f5544919939abc

2022-10-18 08:26 UTC, Sherif-Elhefnawy commented
Thank you for adding the navigation, now please squash all 3 commits into one commit with the appropriate message for the feature :)

2022-10-20 09:07 UTC, Sherif-Elhefnawy approved these changes

2022-10-20 09:21 UTC, Sherif-Elhefnawy approved these changes

2022-10-20 10:54 UTC, merged

2022-10-20 11:04 UTC, Sherif-Elhefnawy commented
Cherry-picked into: 
10.8.x: 3d346c1435cbc2b291506c6ccd37d3f806270ac8
master: 60dba64a2d45fb6e93aa5bf2907bd3746524f133