feat(chart): chart selection area animation
dynatrace-oss/barista pull request #600
Opened 2020-02-14 13:10 UTC by peter-affenzeller

### <strong>Pull Request</strong>

Depends on #594 

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Type of PR

Feature (non-breaking change which adds functionality)

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

2020-03-17 08:16 UTC, ffriedl89 commented
Blocked by #594

2020-04-14 07:48 UTC, ffriedl89 commented
@peter-affenzeller The blocker is now merged - this can be continued :)

2020-05-05 07:42 UTC, lukasholzer commented
Please rebase your branch with the latest master, then perform and install and run `yarn format --all` to get the latest formatting changes that were introduced with the version upgrade of prettier to 2.0. This update was necessary to be compatible with the latest typescript version that we are using. Furthermore, we improved the angular template formatting!

2020-05-11 06:27 UTC, tomheller commented
@peter-affenzeller you have re-requested the review but the PR is still marked as WIP. 
Do you want us to review?

2020-05-11 06:31 UTC, peter-affenzeller commented
@tomheller yes please. it's also no longer blocked since #594 is already merged

2020-05-26 07:08 UTC, lukasholzer commented on libs/barista-components/chart/src/selection-area/selection-area-overlay-ref.ts
> +  }
You don't have Angular lifecycles in pure classes as it is not a part in the Angular Dependency Injection Tree.

You have to handle destroy on your own so please create a destroy method that is called in an `ngOnDestroy` of the wrapping Angular Component.

A class is only used to hold a data state in angular just a better object.

2020-05-26 07:08 UTC, lukasholzer commented on libs/barista-components/chart/src/selection-area/selection-area-overlay-ref.ts
> +export class DtChartSelectionAreaOverlayRef implements OnDestroy {
Please remove implements as it is a normal class and not a Component or Service – therefore you have No Angular Lifecycle methods.

2020-08-27 12:45 UTC, heartdisease requested changes

2020-08-27 12:45 UTC, heartdisease commented on libs/barista-components/chart/src/selection-area/selection-area-container.ts
> +    if (this._portalOutlet.hasAttached()) {
From what I've heard, the new policy is to never break a page by throwing errors. Maybe we should also consider logging an error message here instead?

2020-09-30 10:18 UTC, rowa-audil approved these changes

2020-10-20 07:28 UTC, peter-affenzeller commented
due to the work on the new components we decided to not continue working on this one.

2020-10-20 07:28 UTC, closed without merging